import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h3 className={styles.title}>Data Fetching</h3>
        <ul>
          <li>
            <Link href={"/client/basic"}>Client Side - useEffect</Link>
          </li>
          <li>
            <Link href={"/client/swr"}>Client Side - SWR</Link>
          </li>
          <li>
            <Link href={"/static"}>Static Site Gen</Link>
          </li>
          <li>
            <Link href={"/server"}>Server Side Gen</Link>
          </li>
        </ul>
      </main>
    </div>
  );
};

export default Home;
